--- #YAML:1.0
name:                Net-Pcap-Reassemble
version:             0.03
abstract:            IP fragment reassembly for Net::Pcap
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Net::Pcap:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
